### ISSUE TITLE
Error while installing on MacOS

### ISSUE THREAD

**Issue by truonghuynhmuni** [dominique-unruh/qrhl-tool#13] opened 2020-09-15 18:52 UTC
The following error appears when I install QRHL on MacOS. It seems that the package only works with Linux, not Darwin.
Thank you very much for considering this issue.

<img width="645" alt="Screen Shot 2020-09-15 at 20 51 17" src="https://user-images.githubusercontent.com/44753753/93252125-5c5ce100-f795-11ea-9b36-af086c6a5b62.png">

**Comment by dominique-unruh** [comment] 2020-09-16 00:33
Version 0.5 (the current release) works only with Linux (it ships it's own Isabelle distribution but contains only the Linux binary).

I have rewritten the Isabelle-interface in the current development version. It might run with MacOS but I have no way to test it. (No Mac available.) If you wish to try, I can provide a binary of the development version.

**Comment by truonghuynhmuni** [comment] 2020-09-16 00:39
Thank you very much. I am willing to try (y).

**Comment by dominique-unruh** [comment] 2020-09-16 01:46
You find the binaries here: https://www.dropbox.com/s/da94s6b80k4bw8u/qrhl.zip?dl=1

Note that the installation procedure has somewhat changed, you now need to download and unpack Isabelle2019 and AFP yourself (see the README).

Let me know if there are any other problems.

At least the contributed example files should work. If you want to execute the HKSU proof (Fujisaki-Okamoto verification) - let me know first, I think those files aren't up-to-date right now for the current development version.

**Comment by geniechu** [comment] 2020-09-16 02:35
Thank you so much for sharing the latest binaries, as I also want to build qrhl tools on Mac OS (ver 0.4 worked well). 

Besides I want to execute the HKSU proof as well. It would be so nice if you update the HKSU proof package for the latest development version.

**Comment by dominique-unruh** [comment] 2020-09-16 08:28
> Thank you so much for sharing the latest binaries, as I also want to build qrhl tools on Mac OS (ver 0.4 worked well).

Does either of the two work? If not, let me know what fails. To build, use the latest master release in git and follow the instructions in the README.md at the end (replacing the version number by "master").

> It would be so nice if you update the HKSU proof package for the latest development version.

Right now, the current HKSU proof hangs somewhere. I am trying to find out where this regression comes from and then I will give you access. But let me know first whether you can run the example.qrhl so that we can check one problem at a time.

**Comment by truonghuynhmuni** [comment] 2020-09-16 08:39
I am not sure if I already successfully installed the package, since I had the following errors when I ran an example.

<img width="612" alt="Screen Shot 2020-09-16 at 10 33 12" src="https://user-images.githubusercontent.com/44753753/93313520-dd08f500-f808-11ea-98e5-5b2715728754.png">

**Comment by dominique-unruh** [comment] 2020-09-16 08:58
What java version do you use? (java -version)

**Comment by truonghuynhmuni** [comment] 2020-09-16 09:25
> What java version do you use? (java -version)

Thank you very much. I also guess the java version is the problem.
I already replaced the default java 10 in macOS with java 14. Everything worked well.
<img width="330" alt="Screen Shot 2020-09-16 at 11 23 51" src="https://user-images.githubusercontent.com/44753753/93318744-59063b80-f80f-11ea-85f0-6dc497863d47.png">

**Comment by dominique-unruh** [comment] 2020-09-16 10:02
Status (mostly for me to keep track):
* Java version 11+ needed. (Because current source uses Path.of which was introduced in Java 11) Either update README or use Paths.get
* To do: Make travis-ci testcases for older Java versions
* To do: Make travis-ci testcases for OS/X
* To do: Update qrhl-tool.conf to give hints about where isabelle-home is on OS/X
* Currently trying to figure out what's wrong with HKSU proof
* To do: Provide working snapshot of HKSU

**Comment by geniechu** [comment] 2020-09-16 10:18
Thank you so much for help. I'm done with QRHL tools version 0.6. Now I can run the example.qrhl as well.
<img width="569" alt="Screen Shot 2020-09-16 at 6 48 05 PM" src="https://user-images.githubusercontent.com/71323605/93324465-e74ee180-f850-11ea-8638-708b20d945da.png">

I'm now excitingly waiting for your new HKSU.

**Comment by dominique-unruh** [comment] 2020-09-16 15:28
The official minimal Java version is now Java 11.

I cannot reproduce the problem I had earlier with the HKSU proof, so I hope it's fixed now.

Please reinstall the qrhl-tool from https://www.dropbox.com/s/da94s6b80k4bw8u/qrhl.zip?dl=1
And use HKSU from the snapshot branch https://github.com/dominique-unruh/hksu-verification/tree/snapshot

**Comment by hien-chu** [comment] 2020-09-16 16:33
Now it absolutely works well! `all.qrhl` is verified!
> Finished and saved current lemma as 'encFO_indcca':
[...] 
EOF
Thank you so much for your enthusiasm! I'm ready to explore your tools and FO verification.

**Comment by dominique-unruh** [comment] 2020-09-16 19:07
Excellent. Assuming it works for everyone in this thread, I'm closing this issue. Please comment if it doesn't work for everyone.

**Closed by dominique-unruh** 2020-09-16 19:07 UTC

**Comment by dominique-unruh** [comment] 2020-11-18 12:19
The newest version (0.6) now incorporates these changes and should run on Windows, Mac, and Linux.

@hien-chu @truonghuynhmuni
